# Generated by Django 4.0.6 on 2022-07-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='d_nutrient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='m_nutrient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='y_nutrient',
            field=models.IntegerField(default=0),
        ),
    ]
